version: 0.2

phases:
  install:
    commands:
      - echo No dependencies to install for static site.
  build:
    commands:
      - echo Build step is not needed for static site.
  post_build:
    commands:
      - echo Build completed. Preparing for deployment.

artifacts:
  files:
    - '**/*'
